[package]
name = "plugy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plugy-core = { path = "./crates/plugy-core", version = "0.1.0" }
plugy-macros = { path = "./crates/plugy-macros", version = "0.1.0" }
plugy-runtime = { path = "./crates/plugy-runtime", version = "0.1.0" }


[workspace]
members = [
    "crates/plugy-core",
    "crates/plugy-macros",
    "crates/plugy-runtime",
    "examples/runner",
    "examples/foo-plugin",
    "examples/shared",
]


[profile.release]
lto = true
