[package]
name = "plugy-core"
version = "0.1.0"
edition = "2021"
readme = "../../README.md"
categories = ["wasm", "plugin", "wasi", "inventory"]
license = "GNU General Public License"
repository = "https://github.com/geofmureithi/plugy"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1", features = ["derive"] }
bincode = "1.3.3"